name: Pre-commit

on:
  pull_request_target:
  push:
    branches: [main]
  # pull_request:
  #   types: [opened, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    # if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: |
            3.11
      - name: Install Dependencies
        run: |
          git config --global user.email "GitHub Action <action@github.com>"
          git config --global user.name "GitHub Action <action@github.com>"
          pip install pre-commit==3.6.0 ruff==0.2.0
          ruff check --fix --unsafe-fixes --config=pyproject.toml .
          git add .
          git diff --staged --quiet || git commit -m ":rainbow: pre-commit
          > Made via .github/workflows/a_pre_commit.yml" || echo "pre-commit: no changes"
      - name: Run pre-commit autoupdate
        run: |
          pre-commit autoupdate
          pre-commit install -c .pre-commit-config.yaml || true
          # pre-commit run -c .pre-commit-config.yaml || true
          git add .
          git diff --staged --quiet || git commit -m ":rainbow: pre-commit
          > Made via .github/workflows/a_pre_commit.yml" || echo "pre-commit: no changes"
      # - name: Pre-commit and auto commit
      #   run: |
      #     pre-commit run --all-files || true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.0.0
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: Update files
          committer: GitHub Action <action@github.com>
          author: GitHub Action <action@github.com>
          signoff: true
          branch: pre-commit
          # base: main
          title: "ðŸ”¨ Update files by <github-actions[bot]>"
          body: |
            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            wait
            in progress
            bot
          draft: false
          delete-branch: true
